### PR TITLE
Leo Yao Daleks

### PR DESCRIPTION
**Pull request by yaol9270**
:ideograph_advantage:

### CODE REVIEW

**Comment by MrLamont-HHSS** [comment]
Your logic looks good Leo but you didn't hand in your Dalek, or Doctor class..... You need to hand these in before I can mark it

**Comment by MrLamont-HHSS** [comment]
Just recommit your files and push them up. It will update this request. Post a comment when you have done that!

**Comment by yaol9270** [comment]
I think I uploaded Daleks and Doctor class. Thanks

**Comment by MrLamont-HHSS** [comment]
Still missing the Doctor class there Leo

**Comment by yaol9270** [comment]
Is it there now? I think I properly did it this time

**Comment by MrLamont-HHSS** [comment]
:+1:

**Pull request closed without merging**
